sudo: false
language: node_js
node_js:
- v5
deploy:
  provider: npm
  email: kermit666@gmail.com
  api_key:
    secure: Mso5FFZ2UrLuknp1GtvQiFL7K1W5ggDlnWRPodEzeal99cLMfOxphjX0zRn0+PEPDOOW2JnPhTyXT1SMdMpXYZ7J5G6JSbPgxH4FxU8G61iB36zKSV86z//SCuPi7FavRhyMeSE2t/EHwxLvBAvahfNOYNUUCcYW1+gy2he2cylFUa0yXrrPDJWj2CkdRg0A+3PTnhLWmNnL8pavk7la/R405iaZFvUeoQbq01BCeZJhSBSFfNLMT46PYYS63GZTuuR7CPyrjIXD0tuTZwC9SJUitz2cgFqI6M1X+rayWAS/3N+Wf6h1rY49PGRqLauMf/meIsE8fi87KMPfdfnP3pSwPS7BKOjOIb0zT5AMjafeJ9HzZUiwd248Okx3RPbQiZSMHdxiyHOHCPzHsiaPcWyeJzIbZ7leBAMRJePeRUasRetUAUTQ8CL/L6gGxftMu7d0xWlEK6Pu4y5m4I7niC70yCnVx39QdrL0q0rnkZMdlTtCwDBqpli0y2NOZ0ugktlZ+87xsUmiTy9j5zMMPoUT5GJ8yAZgAudYZI69AVQPOcboxTIxGTXUfAUeDYkasoZC419WFFicP0rOijjb9n0C9Gix8N6uNXDRMyj4v7wuR239qyubZsn/IwuKmBQoyyPgu8oUCDBdvUnOpR60Mg7awGcG6LuMsE8ANmebdlY=
  on:
    tags: true
    branch: master
