db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: secret
web:
  build: .
  image: <%= project_name %>
  env_file: .env
  command: python manage.py runserver 0.0.0.0:8000
  environment:
    DATABASE_URL: psql://secret:postgres@db/postgres
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
cli:
  image: <%= project_name %>
  env_file: .env
  entrypoint: python manage.py
  environment:
    DATABASE_URL: psql://postgres@db/postgres
  volumes:
    - .:/code
  links:
    - db
